#!/bin/zsh
# Flush "automation drift" in one deliberate step: stage + commit the
# automation-WRITTEN data/output files that the launchd jobs churn (daily price
# refresh, RC ingest, the daily sp_scan, the weekly news-pull, the preflight).
#
# Run it whenever you want a clean tree:  ./scripts/commit_drift.sh
# Commit only — PUSH STAYS MANUAL (push is a deliberate event; the helper just
# prints the command). No cron calls this; you run it by hand.
#
# DELIBERATELY EXCLUDED:
#   - decisions/*_log.md — partly human-written (the **Decision:** annotations; since
#     2026-09-02 a run writes only the moved names' logs, owner F12);
#     commit those yourself with the annotation, not via a blind drift sweep.
#   - state/* — already gitignored (machine-local).
#   - per-name outputs/*_fv_report.* / *_scenarios.* — regenerated by a manual
#     pipeline run; commit those with whatever input change drove them.

set -eu

PROJECT="${HOME}/Projects/crude-tanker-fv"
cd "$PROJECT"

# Promote the state-side EDGAR manifest to its tracked snapshot (WO2 2.3,
# R-2): the Action's --pure FILING checks see pushed state only — coverage
# lags to the last push by design; the local sentinel is the primary pager.
if [[ -f state/edgar_manifest.jsonl ]]; then
  ./.venv/bin/python - <<'PYEOF'
import json, pathlib
lines = [json.loads(l) for l in pathlib.Path("state/edgar_manifest.jsonl").read_text().splitlines() if l.strip()]
out = pathlib.Path("inputs/filings/_manifest.json")
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(lines, indent=1) + "\n")
print(f"commit_drift: promoted edgar manifest snapshot ({len(lines)} arrivals)")
PYEOF
fi

# The recurring automation-written tracked files — read from the ONE
# canonical list (scripts/drift_files.txt, WO2 2026-07-06; the price-cron
# guard and sentinel meta-mode read the same file).
FILES=("${(@f)$(grep -v '^#' scripts/drift_files.txt | grep -v '^$')}")

# Stage only those that exist AND actually changed (unstaged or staged).
to_add=()
for f in "${FILES[@]}"; do
  [[ -f "$f" ]] || continue
  if ! git diff --quiet -- "$f" || ! git diff --cached --quiet -- "$f"; then
    to_add+=("$f")
  fi
done

if (( ${#to_add[@]} == 0 )); then
  echo "commit_drift: no automation drift to commit."
  exit 0
fi

echo "commit_drift: staging ${#to_add[@]} file(s):"
printf '  %s\n' "${to_add[@]}"

git add -- "${to_add[@]}"
git commit -m "chore(automation): flush data/output drift ($(date '+%Y-%m-%d'))

Routine automation-written files (daily price refresh / RC ingest / sp_scan /
linked-report manifest / preflight / FFA queue). Decision logs excluded
(committed deliberately with their annotations). Push stays manual."

echo
echo "Committed. Push when ready:  git push origin main"
