#!/bin/zsh
# Flush "automation drift" in one deliberate step: stage + commit the
# automation-WRITTEN data/output files that the launchd jobs churn (daily price
# refresh, RC ingest, the daily sp_scan, the weekly news-pull, the preflight).
#
# Run it whenever you want a clean tree:  ./scripts/commit_drift.sh
# Commit only — PUSH STAYS MANUAL (push is a deliberate event; the helper just
# prints the command). No cron calls this; you run it by hand.
#
# DELIBERATELY EXCLUDED:
#   - decisions/*_log.md — partly human-written (the **Decision:** annotations);
#     commit those yourself with the annotation, not via a blind drift sweep.
#   - state/* — already gitignored (machine-local).
#   - per-name outputs/*_fv_report.* / *_scenarios.* — regenerated by a manual
#     pipeline run; commit those with whatever input change drove them.

set -eu

PROJECT="${HOME}/Projects/crude-tanker-fv"
cd "$PROJECT"

# The recurring automation-written tracked files (the cron drifters).
FILES=(
  inputs/market_data/prices_daily.yaml
  inputs/market_data/baltic_indexes_daily.csv
  inputs/market_data/transactions/_scan_state.json
  inputs/research_pareto/_manifest.json
  outputs/sp_print_candidates.md
  outputs/refresh_checklist.md
  outputs/ffa_ocr_queue.md
  outputs/pareto_daily_links.json
)

# Stage only those that exist AND actually changed (unstaged or staged).
to_add=()
for f in "${FILES[@]}"; do
  [[ -f "$f" ]] || continue
  if ! git diff --quiet -- "$f" || ! git diff --cached --quiet -- "$f"; then
    to_add+=("$f")
  fi
done

if (( ${#to_add[@]} == 0 )); then
  echo "commit_drift: no automation drift to commit."
  exit 0
fi

echo "commit_drift: staging ${#to_add[@]} file(s):"
printf '  %s\n' "${to_add[@]}"

git add -- "${to_add[@]}"
git commit -m "chore(automation): flush data/output drift ($(date '+%Y-%m-%d'))

Routine automation-written files (daily price refresh / RC ingest / sp_scan /
linked-report manifest / preflight / FFA queue). Decision logs excluded
(committed deliberately with their annotations). Push stays manual."

echo
echo "Committed. Push when ready:  git push origin main"
